fastlane_version "1.39.0"

before_all do
  ensure_git_status_clean
end

desc "Release a new beta version on TestFlight"
lane :deploy do
  increment_build_number

  gym scheme: "Cerberus", configuration: "Release"
  testflight skip_submission: true

  clean_build_artifacts

  commit_version_bump
  push_to_git_remote
end

error do |lane, exception|
  reset_git_repo
end
