fastlane_version "1.39.0"

desc "Release a new beta version on TestFlight"
lane :deploy do
  ensure_git_status_clean

  increment_build_number

  gym(
    scheme: "Cerberus",
    configuration: "Release"
  )

  testflight

  commit_version_bump
  push_to_git_remote

  clean_build_artifacts
end
